"""
Auto-generated type stubs for prompteer prompts.
DO NOT EDIT THIS FILE MANUALLY.

Generated by: prompteer generate-types
Generated at: 2026-09-02 11:46:05
Source directory: /Users/mintae/Documents/Develop/side-projects/prompteer/examples/prompts
"""

from typing import Any
from typing import Union

class _BlocksProxy:
    """Proxy for blocks/ directory."""

    def codeReview(
        self,
        checklist: list[Any] = [],
        code: str = "",
        include_checklist: bool = False,
        language: str = "",
        tone: str = "",
        **kwargs: Any
    ) -> str:
        """
        Code review prompt with conditional checklist

        Args:
            checklist: List of review items
            code: Code to review
            include_checklist: Include review checklist
            language: Programming language
            tone: Review tone (friendly, strict, neutral)
            **kwargs: Additional variables
        """
        ...

    def greeting(
        self,
        formal: bool = False,
        name: str = "",
        title: str = "",
        **kwargs: Any
    ) -> str:
        """
        Greeting prompt with conditional formality

        Args:
            formal: Use formal greeting style
            name: User's name
            title: User's title (for formal greetings)
            **kwargs: Additional variables
        """
        ...

    def multilingual(
        self,
        examples: list[Any] = [],
        include_examples: bool = False,
        languages: list[Any] = [],
        primary_language: str = "",
        **kwargs: Any
    ) -> str:
        """
        Multilingual assistant system prompt

        Args:
            examples: Example phrases in each language
            include_examples: Include example phrases
            languages: Supported languages
            primary_language: Primary response language
            **kwargs: Additional variables
        """
        ...

    def taskList(
        self,
        show_priority: bool = False,
        tasks: list[Any] = [],
        title: str = "",
        **kwargs: Any
    ) -> str:
        """
        Task list prompt with loop

        Args:
            show_priority: Show priority levels
            tasks: List of task items
            title: List title
            **kwargs: Additional variables
        """
        ...

class _ChatProxy:
    """Proxy for chat/ directory."""

    def system(
        self,
        personality: str = "",
        role: str = "",
        **kwargs: Any
    ) -> str:
        """
        System message prompt

        Args:
            personality: AI personality traits
            role: AI role description
            **kwargs: Additional variables
        """
        ...

    def userQuery(
        self,
        context: str = "",
        question: str = "",
        **kwargs: Any
    ) -> str:
        """
        User query prompt

        Args:
            context: Additional context
            question: User's question
            **kwargs: Additional variables
        """
        ...

class _CodeReviewProxy:
    """Proxy for codeReview/ directory."""

    def reviewRequest(
        self,
        code: str = "",
        focus_areas: str = "",
        language: str = "",
        **kwargs: Any
    ) -> str:
        """
        Code review request prompt

        Args:
            code: Code to review
            focus_areas: Areas to focus on
            language: Programming language
            **kwargs: Additional variables
        """
        ...

class _TranslationProxy:
    """Proxy for translation/ directory."""

    def translate(
        self,
        source_lang: str = "",
        style: str = "",
        target_lang: str = "",
        text: str = "",
        **kwargs: Any
    ) -> str:
        """
        Translation prompt

        Args:
            source_lang: Source language
            style: Translation style (formal/casual)
            target_lang: Target language
            text: Text to translate
            **kwargs: Additional variables
        """
        ...

class Prompteer:
    """prompteer's main class

    Args:
        base_path: Root directory containing prompt files
        encoding: File encoding (default: 'utf-8')
    """

    @property
    def blocks(self) -> _BlocksProxy: ...

    @property
    def chat(self) -> _ChatProxy: ...

    @property
    def codeReview(self) -> _CodeReviewProxy: ...

    @property
    def translation(self) -> _TranslationProxy: ...


def create_prompts(base_path: str, encoding: str = "utf-8") -> Prompteer:
    """Create a Prompteer instance with automatic type inference.

    This is a convenience factory function that creates a Prompteer instance
    and returns it with proper type hints.

    Usage:
        >>> from prompts import create_prompts
        >>> prompts = create_prompts("./prompts")
        >>> prompts.chat.system(role="...", personality="...")  # Full autocomplete!

    Args:
        base_path: Root directory containing prompt files
        encoding: File encoding for reading prompts (default: 'utf-8')

    Returns:
        Prompteer instance with full type hints
    """
    ...