"""Tests for type_generator module."""

from __future__ import annotations

from pathlib import Path

import pytest

from prompteer.type_generator import (
    TypeStubGenerator,
    get_default_value,
    get_python_type,
)


class TestGetPythonType:
    """Tests for get_python_type function."""

    def test_string_type(self) -> None:
        """Test string type mapping."""
        assert get_python_type("str") == "str"

    def test_int_type(self) -> None:
        """Test int type mapping."""
        assert get_python_type("int") == "int"

    def test_float_type(self) -> None:
        """Test float type mapping."""
        assert get_python_type("float") == "float"

    def test_bool_type(self) -> None:
        """Test bool type mapping."""
        assert get_python_type("bool") == "bool"

    def test_number_type(self) -> None:
        """Test number type mapping to Union."""
        assert get_python_type("number") == "Union[int, float]"

    def test_any_type(self) -> None:
        """Test any type mapping."""
        assert get_python_type("any") == "Any"

    def test_unknown_type(self) -> None:
        """Test unknown type defaults to Any."""
        assert get_python_type("unknown") == "Any"


class TestGetDefaultValue:
    """Tests for get_default_value function."""

    def test_string_default(self) -> None:
        """Test string default value."""
        assert get_default_value("str") == '""'

    def test_int_default(self) -> None:
        """Test int default value."""
        assert get_default_value("int") == "0"

    def test_float_default(self) -> None:
        """Test float default value."""
        assert get_default_value("float") == "0.0"

    def test_bool_default(self) -> None:
        """Test bool default value."""
        assert get_default_value("bool") == "False"


class TestTypeStubGenerator:
    """Tests for TypeStubGenerator class."""

    def test_scan_directory(self) -> None:
        """Test directory scanning."""
        generator = TypeStubGenerator(Path("tests/fixtures/prompts"))
        structure = generator.scan_directory(Path("tests/fixtures/prompts"))

        assert "simple" in structure
        assert "with-variables" in structure
        assert "with-metadata" in structure
        assert "nested" in structure

    def test_generate_type_stub(self, tmp_path: Path) -> None:
        """Test type stub generation."""
        generator = TypeStubGenerator(Path("tests/fixtures/prompts"))
        output_path = tmp_path / "test.pyi"

        generator.generate_type_stub(output_path)

        assert output_path.exists()
        content = output_path.read_text()

        # Check header
        assert "Auto-generated type stubs" in content
        assert "DO NOT EDIT THIS FILE MANUALLY" in content

        # Check imports
        assert "from typing import Any" in content

        # Check main class
        assert "class Prompteer:" in content

    def test_generated_stub_has_correct_types(self, tmp_path: Path) -> None:
        """Test that generated stub has correct type annotations."""
        generator = TypeStubGenerator(Path("tests/fixtures/prompts"))
        output_path = tmp_path / "test.pyi"

        generator.generate_type_stub(output_path)
        content = output_path.read_text()

        # Should have methods for prompt files
        assert "def simple" in content or "def simple(" in content
        assert "def withVariables" in content or "def withVariables(" in content

        # Metadata prompt should have typed parameters
        if "def withMetadata" in content:
            # Check for type annotations
            assert "int" in content or "float" in content


class TestNestedDynamicStubs:
    """Stub generation for recursive dynamic routes."""

    @staticmethod
    def _write(root, relative: str, content: str) -> None:
        """Create a prompt file, making parent directories as needed."""
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)

    def _generate(self, tmp_path, tree: dict) -> str:
        """Build a prompt tree and return the generated stub content."""
        prompts_dir = tmp_path / "prompts"
        for relative, content in tree.items():
            self._write(prompts_dir, relative, content)

        generator = TypeStubGenerator(prompts_dir)
        output = tmp_path / "prompts.pyi"
        generator.generate_type_stub(output)
        return output.read_text()

    def test_nested_params_appear_in_one_signature(self, tmp_path) -> None:
        """Both routing parameters are required by the generated method."""
        content = self._generate(
            tmp_path,
            {
                "q/[type]/basic/[lang]/ko/user.md": "ko",
                "q/[type]/basic/[lang]/en/user.md": "en",
            },
        )

        assert 'type: Literal["basic"]' in content
        assert 'lang: Literal["en", "ko"]' in content

    def test_intermediate_static_dir_becomes_a_proxy(self, tmp_path) -> None:
        """Static directories under value directories merge into one class."""
        content = self._generate(
            tmp_path,
            {
                "q/[type]/basic/extra/user.md": "basic extra",
                "q/[type]/advanced/extra/user.md": "advanced extra",
            },
        )

        assert "class _QExtraProxy:" in content
        assert "def extra(self) -> _QExtraProxy: ..." in content
        assert 'type: Literal["advanced", "basic"]' in content

    def test_branches_needing_different_params_become_overloads(self, tmp_path) -> None:
        """A prompt reachable with and without an inner parameter overloads."""
        content = self._generate(
            tmp_path,
            {
                "q/[type]/basic/[lang]/ko/user.md": "ko",
                "q/[type]/advanced/user.md": "advanced",
            },
        )

        assert "from typing import overload" in content
        assert content.count("@overload") == 2
        assert 'type: Literal["advanced"]' in content
        assert 'type: Literal["basic"]' in content

    def test_default_directory_adds_no_literal_value(self, tmp_path) -> None:
        """The fallback subtree is not a selectable routing value."""
        content = self._generate(
            tmp_path,
            {
                "q/[type]/basic/user.md": "basic",
                "q/[type]/default/user.md": "fallback",
            },
        )

        assert 'type: Literal["basic"]' in content
        assert '"default"' not in content

    def test_attribute_names_are_lowercase(self, tmp_path) -> None:
        """A capitalised tree still yields conventional camelCase attributes."""
        content = self._generate(tmp_path, {"Chat/System.md": "x"})

        assert "def chat(self) -> _ChatProxy: ..." in content
        assert "def system(" in content

    def test_case_collision_is_warned(self, tmp_path) -> None:
        """Unportable trees are reported instead of silently generated.

        The colliding entries are passed directly because a case-insensitive
        filesystem cannot hold both of them.
        """
        generator = TypeStubGenerator(tmp_path)
        generator._warn_on_case_collisions(
            tmp_path, [tmp_path / "Chat", tmp_path / "chat", tmp_path / "other"]
        )

        assert len(generator.warnings) == 1
        assert "differ only by case" in generator.warnings[0]
        assert "'Chat', 'chat'" in generator.warnings[0]

    def test_directory_and_file_name_clash_is_warned(self, tmp_path) -> None:
        """A directory and a prompt file sharing a name is reported."""
        prompts_dir = tmp_path / "prompts"
        self._write(prompts_dir, "chat/system.md", "x")
        self._write(prompts_dir, "chat.md", "x")

        generator = TypeStubGenerator(prompts_dir)
        generator.generate_type_stub(tmp_path / "prompts.pyi")

        assert any("share this name" in warning for warning in generator.warnings)
